"""empty message

Revision ID: 4d1bf399fd4b
Revises: e414cbbb389c
Create Date: 2022-05-09 23:09:16.046241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d1bf399fd4b'
down_revision = 'e414cbbb389c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('height', sa.String(length=120), nullable=False),
    sa.Column('mass', sa.String(length=120), nullable=False),
    sa.Column('hair_color', sa.String(length=120), nullable=False),
    sa.Column('skin_color', sa.String(length=120), nullable=False),
    sa.Column('eye_color', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eye_color'),
    sa.UniqueConstraint('eye_color'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('hair_color'),
    sa.UniqueConstraint('hair_color'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('skin_color'),
    sa.UniqueConstraint('skin_color')
    )
    op.drop_index('eye_color', table_name='characters')
    op.drop_index('eye_color_2', table_name='characters')
    op.drop_index('gender', table_name='characters')
    op.drop_index('gender_2', table_name='characters')
    op.drop_index('hair_color', table_name='characters')
    op.drop_index('hair_color_2', table_name='characters')
    op.drop_index('height', table_name='characters')
    op.drop_index('height_2', table_name='characters')
    op.drop_index('mass', table_name='characters')
    op.drop_index('mass_2', table_name='characters')
    op.drop_index('name', table_name='characters')
    op.drop_index('name_2', table_name='characters')
    op.drop_index('skin_color', table_name='characters')
    op.drop_index('skin_color_2', table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('height', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('mass', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('hair_color', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('skin_color', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('eye_color', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('skin_color_2', 'characters', ['skin_color'], unique=False)
    op.create_index('skin_color', 'characters', ['skin_color'], unique=False)
    op.create_index('name_2', 'characters', ['name'], unique=False)
    op.create_index('name', 'characters', ['name'], unique=False)
    op.create_index('mass_2', 'characters', ['mass'], unique=False)
    op.create_index('mass', 'characters', ['mass'], unique=False)
    op.create_index('height_2', 'characters', ['height'], unique=False)
    op.create_index('height', 'characters', ['height'], unique=False)
    op.create_index('hair_color_2', 'characters', ['hair_color'], unique=False)
    op.create_index('hair_color', 'characters', ['hair_color'], unique=False)
    op.create_index('gender_2', 'characters', ['gender'], unique=False)
    op.create_index('gender', 'characters', ['gender'], unique=False)
    op.create_index('eye_color_2', 'characters', ['eye_color'], unique=False)
    op.create_index('eye_color', 'characters', ['eye_color'], unique=False)
    op.drop_table('Characters')
    # ### end Alembic commands ###
