"""empty message

Revision ID: aa0992c2183f
Revises: 4d1bf399fd4b
Create Date: 2022-05-09 23:22:29.201388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0992c2183f'
down_revision = '4d1bf399fd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('eye_color', table_name='Characters')
    op.drop_index('eye_color_2', table_name='Characters')
    op.drop_index('gender', table_name='Characters')
    op.drop_index('gender_2', table_name='Characters')
    op.drop_index('hair_color', table_name='Characters')
    op.drop_index('hair_color_2', table_name='Characters')
    op.drop_index('height', table_name='Characters')
    op.drop_index('height_2', table_name='Characters')
    op.drop_index('mass', table_name='Characters')
    op.drop_index('mass_2', table_name='Characters')
    op.drop_index('skin_color', table_name='Characters')
    op.drop_index('skin_color_2', table_name='Characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('skin_color_2', 'Characters', ['skin_color'], unique=False)
    op.create_index('skin_color', 'Characters', ['skin_color'], unique=False)
    op.create_index('mass_2', 'Characters', ['mass'], unique=False)
    op.create_index('mass', 'Characters', ['mass'], unique=False)
    op.create_index('height_2', 'Characters', ['height'], unique=False)
    op.create_index('height', 'Characters', ['height'], unique=False)
    op.create_index('hair_color_2', 'Characters', ['hair_color'], unique=False)
    op.create_index('hair_color', 'Characters', ['hair_color'], unique=False)
    op.create_index('gender_2', 'Characters', ['gender'], unique=False)
    op.create_index('gender', 'Characters', ['gender'], unique=False)
    op.create_index('eye_color_2', 'Characters', ['eye_color'], unique=False)
    op.create_index('eye_color', 'Characters', ['eye_color'], unique=False)
    # ### end Alembic commands ###
